# navbar
menu:
  Home: /
  Archives: /archives/
  #Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# theme color
# Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme_color: Mint Green
# theme_headerlink: ยง

# comments
comments:
  post: true
  about: true

# article directory sidebar
sidebar: true

# Analytics
## Baidu Analytics
# baidu_analytics: Your baidu Analytics ID
## Google Analytics
# google_analytics: Your Google Analytics ID

# Comments
## Duoshuo
# duoshuo_shortname: Your duoshuo ID
## Disqus
disqus_shortname: ruikye

# Social links
social:
  email: kyonggen@email.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: 'https://github.com/rakkang/'
  # weibo: 
  # zhihu: 
  # rss: /atom.xml